services:
  e2vid:
    image: kkdocking/e2vid:latest
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - e2vid_jobs:/app/.jobs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  e2vid_jobs:
